"""add_ai_specs_to_products

Revision ID: 353477288a44
Revises: 3184d61677fb
Create Date: 2026-05-18 11:58:44.757334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353477288a44'
down_revision: Union[str, Sequence[str], None] = '3184d61677fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ai_specs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ai_specs')
    # ### end Alembic commands ###
